import { Column, Entity, ManyToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Field, Float, ObjectType } from '@nestjs/graphql';
import { User } from '../../user/entities';

@Entity('product')
@ObjectType()
export class Product {
  @PrimaryGeneratedColumn('uuid', { name: 'product_id' })
  @Field({ description: 'This is an autogenerated id' })
  id: string;

  @Column()
  @Field()
  name: string;

  @Column('decimal', { precision: 2 })
  @Field((type) => Float)
  price: number;

  @ManyToMany(() => User, (user) => user.order)
  @Field((type) => [User], {
    nullable: true,
    description:
      'Users associated with the product, in case we want to see all the users that ordered that product.',
  })
  user: User[];
}
